title: Settings
icon: mdi:cogs
path: settings
panel: true
cards:
  - type: custom:layout-card
    layout: auto
    cards:
      - type: vertical-stack
        cards:
          - !include links_card.yaml
          - type: entities
            title: Debugging
            show_header_toggle: false
            entities:
              - input_boolean.test

      - type: vertical-stack
        cards:
          - type: custom:auto-entities
            card:
              type: entities
              title: Low Battery
              show_header_toggle: false
            filter:
              include:
                - entity_id: "*battery*"
                  state: "<= 30"
                  sort:
                    method: state
                    numeric: true
                - attributes:
                    battery_level: "<= 30"
                  options:
                    type: custom:secondaryinfo-entity-row
                    secondary_info: "[[ {entity}.attributes.battery_level ]] %"
                  sort:
                    method: attribute
                    attribute: battery_level
                    numeric: true
              exclude:
                - entity_id: "zwave.*"
            show_empty: true
            unique: true


      - type: vertical-stack
        cards:
          - type: custom:auto-entities
            card:
              type: entities
              title: Power consumption
              show_header_toggle: false
            filter:
              include:
                - entity_id: sensor.daily_energy_consumption
                - entity_id: sensor.monthly_energy_consumption
                - entity_id: "*_power"
              exclude:
                - entity_id: "*_2"
                - entity_id: "*_management"

      - type: vertical-stack
        cards:
          - type: custom:grocy-chores-card
            title: All chores
            entity: sensor.grocy_chores
            user_id: 2

          - type: custom:gui-sandbox