resources:
  !include lovelace/resources/resources.yaml

cch:
  disable: false
  header: true
  menu: show
  sidebar_swipe: true
  notifications: show
  voice: hide
  options: clock
  clock_format: 24
  clock_date: true
  date_locale: sv-SE
  swipe: true
  exceptions:
    - conditions:
        user: dashboard
      config:
        show_tabs: 9
        kiosk_mode: true

button_card_templates:
  !include lovelace/button_card_templates/button_card_templates.yaml

decluttering_templates:
  !include lovelace/decluttering_templates/decluttering_templates.yaml

title: Home
background: var(--background)
views:
  - !include lovelace/00_home_view.yaml
  - !include lovelace/10_home_info_view.yaml
  - !include lovelace/20_lights_view.yaml
  - !include lovelace/30_system_info_view.yaml
  - !include lovelace/31_system_graphs.yaml
  - !include lovelace/40_camera_view.yaml
  - !include lovelace/3d_printer.yaml
  - !include lovelace/80_automations_view.yaml
  - !include lovelace/99_settings_view.yaml
  - !include lovelace/102_nest_dashboard.yaml
  - !include lovelace/01_homekit_view.yaml

  - !include lovelace/media.yaml
