automation:
  - alias: '[House] Cleaning Mode'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.unlocked_by
        to: 'Cleaners'
    condition:
    - condition: state
      entity_id: calendar.cleaning_day
      state: 'on'
    action:
      - service: script.turn_on
        entity_id: script.cleaning_time
      - service: homeassistant.turn_off
        entity_id: automation.ring_doorbell_motion_lights
      - service: notify.ios_isabellas_iphone_x
        data_template:
          title: 'Cleaning time'
          message: 'Cleaners have arrived'

  - alias: '[House] Cleaning Mode Off'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: calendar.house_cleaning
        to: 'off'
    action:
      - service: homeassistant.turn_on
        entity_id: automation.ring_doorbell_motion_lights
      - service: notify.ios_isabellas_iphone_x
        data_template:
          title: 'Cleaning time over'
          message: ''
