sensor:
  - platform: template
    sensors:
      passage_movement:
        friendly_name: 'Passage Movement'
        entity_id: "binary_sensor.passage_pir_sensor"
        value_template: '{% if is_state("binary_sensor.passage_pir_sensor", "on") %}Movement detected{% else %}No movement{% endif %}'
        icon_template: '{% if is_state("binary_sensor.passage_pir_sensor", "on") %}mdi:run-fast{% else %}mdi:sleep{% endif %}'

      upstairs_hallway_movement:
        friendly_name: 'Upstairs Hallway Movement'
        entity_id: "binary_sensor.upstairs_hallway_pir_sensor"
        value_template: '{% if is_state("binary_sensor.upstairs_hallway_pir_sensor", "on") %}Movement detected{% else %}No movement{% endif %}'
        icon_template: '{% if is_state("binary_sensor.upstairs_hallway_pir_sensor", "on") %}mdi:run-fast{% else %}mdi:sleep{% endif %}'

      stefans_office_movement:
        friendly_name: 'Stefans Office Movement'
        entity_id: "binary_sensor.stefans_room_motion"
        value_template: '{% if is_state("binary_sensor.stefans_room_motion", "on") %}Movement detected{% else %}No movement{% endif %}'
        icon_template: '{% if is_state("binary_sensor.stefans_room_motion", "on") %}mdi:run-fast{% else %}mdi:sleep{% endif %}'   

      living_room_axis_movement:
        friendly_name: 'Living Room Movement'
        entity_id: "rbinary_sensor.living_room_axis_motion_0"
        value_template: '{% if is_state("rbinary_sensor.living_room_axis_motion_0", "on") %}Movement detected{% else %}No movement{% endif %}'
        icon_template: '{% if is_state("rbinary_sensor.living_room_axis_motion_0", "on") %}mdi:run-fast{% else %}mdi:sleep{% endif %}'   

      living_room_axis_movement_2:
        friendly_name: 'Living Room Movement 2'
        entity_id: "binary_sensor.passage_axis_motion_0"
        value_template: '{% if is_state("binary_sensor.passage_axis_motion_0", "on") %}Movement detected{% else %}No movement{% endif %}'
        icon_template: '{% if is_state("binary_sensor.passage_axis_motion_0", "on") %}mdi:run-fast{% else %}mdi:sleep{% endif %}'   

      house_movement:
        friendly_name: 'House Movement'
        entity_id: binary_sensor.passage_pir_sensor, binary_sensor.upstairs_hallway_pir_sensor, binary_sensor.stefans_room_motion, binary_sensor.living_room_axis_motion_0, binary_sensor.passage_axis_motion_0
        value_template: >-
          {% if is_state('binary_sensor.passage_pir_sensor', 'on') or is_state("binary_sensor.upstairs_hallway_pir_sensor", "on") or is_state("binary_sensor.stefans_room_motion", "on") or is_state("binary_sensor.living_room_axis_motion_0", "on") or is_state("binary_sensor.passage_axis_motion_0", "on") %}
            Movement detected
          {% else %}
            No movement
          {% endif %}