homeassistant:
  customize:
    sensor.bedroom_temperature:
      friendly_name: Bedroom
    sensor.passage_temperature:
      friendly_name: Passage
    sensor.downstairs_bathroom_temperature:
      friendly_name: Downstairs Bathroom
    sensor.stefan_temperature:
      friendly_name: Stefans Room

    sensor.humidity_158d0001fd83e7:
      friendly_name: Stefans Room Humidity
      icon: mdi:water-percent
    sensor.humidity_158d0001235510:
      friendly_name: Bedroom Humidity
      icon: mdi:water-percent
    sensor.humidity_158d000123552c:
      friendly_name: Passage Humidity
      icon: mdi:water-percent
    sensor.humidity_158d0001a2a899:
      friendly_name: Downstairs Bathroom Humidity
      icon: mdi:water-percent

    sensor.illumination_34ce008bfc4b:
      friendly_name: Upstairs Hallway Lux
      icon: mdi:theme-light-dark
    sensor.illumination_158d000165ff1f:
      friendly_name: Living Room Lux 
      icon: mdi:theme-light-dark
    sensor.illumination_158d0001a66256:
      friendly_name: Hallway Lux
      icon: mdi:theme-light-dark


  customize_glob:
    sensor.*temperature*:
      templates:
        hs_color: "if (state == 23) return [0, 0];
        else if (state > 23) return [40, 70];
        else if (state > 25) return [0, 85];"